name: CDK Deployment Readiness

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: us-east-1

jobs:
  validate-deployment:
    name: Validate Deployment
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: ${{ github.event.inputs.target_environment || 'staging' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and Dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g aws-cdk
          npm install

      - name: Synthesize CDK Stack (Dry Run)
        run: npx cdk synth --context environment=${{ env.TARGET_ENV }}

      - name: Check for CDK Stack Differences
        run: |
          stack_name="mentorship-staging"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            stack_name="mentorship-production"
          fi
          echo "Running CDK diff on stack: $stack_name"
          npx cdk diff $stack_name
